/**
 * @desc: candidateItems
 * @author: lzx
 * @date: 2017/3/23 14:34
 */

module.exports = [
  { cn: '产品经理', en: 'Product Manager', phonetic: 'chanpinjingli' },
  { cn: '软件工程师', en: 'Software Engineer' },
  { cn: '工业设计师', en: 'Industrial Designer' },
  { cn: '数据库管理员', en: 'Database Administrator' },
  { cn: '产品运营', en: 'Product Operations', phonetic: 'chanpinyunying' },
  { cn: '高级保洁主管', en: 'Senior Cleaning Supervisor' },
  { cn: '茶水间主任', en: 'Perennial Director' },
  { cn: '安保经理', en: 'Security Manager' },
  { cn: '安保队长', en: 'Security Captain' },
  { cn: '程序员', en: 'Programmer' },
  { cn: '内容运营', en: 'Content Operations' },
  { cn: '新媒体运营', en: 'New Media Operations' },
  { cn: '软件开发', en: 'Software Development' },
  { cn: '产品总监', en: 'Product Director' },
  { cn: '活动策划', en: 'Event planner' },
  { cn: '前端开发', en: 'Front-end Developer' },
  { cn: 'HR业务伙伴', en: 'HRBP' },
  { cn: '人力资源HR', en: 'Human Resource Officer' },
  { cn: '行政助理', en: 'Administrative Assistant' },
  { cn: '总裁秘书', en: 'President Secretary' },
  { cn: '设计总监', en: 'Design Director' },
  { cn: '平面设计师', en: 'Graphic Designer' },
  { cn: '设计师', en: 'Designer' },
  { cn: '市场推广', en: 'Marketing Specialist' },
  { cn: '市场总监', en: 'Marketing Director' },
  { cn: '市场策划', en: 'Marketing Specialist' },
  { cn: '销售总监', en: 'Sales Director' },
  { cn: '总经理助理', en: 'General Manager\'s Assistant' },
  { cn: '人力资源部经理', en: 'Human Resources Manager' },
  { cn: '行政经理', en: 'Administrative Dep.Manager' },
  { cn: '秘书', en: 'Secretary' },
  { cn: '高级顾问', en: 'Senior Consultant' },
  { cn: '销售工程师', en: 'Sales Engineer' },
  { cn: '区域销售经理', en: 'Regional Sales Manager' },
  { cn: '销售部经理', en: 'Sales Manager' },
  { cn: '公关部经理', en: 'Manager for Public Relations' },
  { cn: '工程部经理', en: 'Chief Engineer' },
  { cn: '保安部经理', en: 'Chief Security Officer' },
  { cn: '财务部经理', en: 'Financial Controller' },
  { cn: '外汇部核算员', en: 'F.X. Settlement Clerk' },
  { cn: '会计', en: 'Accountant' },
  { cn: 'IT工程师', en: 'IT Engineer' },
  { cn: '技术服务工程师', en: 'Technician Service Engineer' },
  { cn: '网络主管', en: 'Network Manage' },
  { cn: '硬件工程师', en: 'Hardware Engineer' },
  { cn: '维修工程师', en: 'Maintenance Engineer' },
  { cn: '研究开发工程师', en: 'Research & Development Engineer' },
  { cn: '项目策划', en: 'Project Staff' },
  { cn: 'UI设计师', en: 'UI Designer' },
  { cn: '交互设计师', en: 'Interaction Designer' },
  { cn: '网页设计师', en: 'Web Designer' },
  { cn: '首席执行官', en: 'CEO' },
  { cn: '首席运营官', en: 'COO' },
  { cn: '首席财务官', en: 'CFO' },
  { cn: '首席技术官', en: 'CTO' },
  { cn: '首席信息官', en: 'CIO' },
  { cn: '创意总监', en: 'Creative Director' },
  { cn: '客户服务总监', en: 'Account Director' },
  { cn: '美术指导', en: 'Art Director' },
  { cn: '司机', en: 'Driver' },
  { cn: '保洁', en: 'Purifier' },
  { cn: '送货员', en: 'Deliveryman' },
  { cn: '食堂大妈', en: 'Canteen Worker' },
  { cn: '采购员', en: 'Buyer' },
  { cn: '电话接线员', en: 'Telephonist' },
  { cn: '电工', en: 'Electrician' },
  { cn: '食堂大叔', en: 'Canteen Worker' },
  { cn: '测试工程师 ', en: 'Test Engineer' },
  { cn: '保洁主管', en: 'cleaning supervisor'},
  { cn: '法务专员', en: 'legal specialist' },
  { cn: '前台', en: 'receptionist' },
  { cn: '行政前台', en: 'Administrative Receptionist' },
  { cn: '前台经理', en: 'Front Desk Manager' }
];
